#! /bin/bash

BIN_DIR="$(pwd)"
MODEL_DIR=$BIN_DIR/model_dir
OMOR_DIR=$BIN_DIR/omor_dir

echo "FinnTreeBank tagger () using OMorFi and FinnPos" 1>&2
echo 1>&2

$BIN_DIR/hfst-optimized-lookup $OMOR_DIR/morphology.omor.hfst |
python3 $BIN_DIR/omorfi2finnpos.py ftb                        |
python3 $BIN_DIR/finnpos-ratna-feats.py $MODEL_DIR/freq_words |
$BIN_DIR/finnpos-label $MODEL_DIR/ftb.omorfi.model            |
python3 $BIN_DIR/finnpos-restore-lemma.py $@

